  // ═══ 联网深度挖掘 · 42个A股因子 ═══

  {
    id: 'f001',
    name: 'Amihud非流动性因子',
    source: 'public',
    origin: '联网挖掘',
    category: '微观结构',
    definition: 'ILLIQ = mean(|daily_return| / dollar_volume) over 20 trading days, where dollar_volume = close × volume',
    applicable: '全市场 · higher为优',
    notes: '来源: Amihud (2002), validated on A-shares: 华泰金工 2023《A股市场微观结构因子研究》, 中金公司 2024 · 方向: higher',
    performance: 'IC≈+0.032, IR≈0.18',
  },
  {
    id: 'f002',
    name: '特质波动率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'IVOL = std(residuals from Fama-French 3-factor regression of daily returns over past 20-60 days). Simplified proxy: std(',
    applicable: '全市场 · lower为优',
    notes: '来源: Ang, Hodrick, Xing & Zhang (2006, 2009); validated on A-shares: 华泰证券 2023《特质波动率因 · 方向: lower',
    performance: 'IC≈-0.045, IR≈-0.25',
  },
  {
    id: 'f003',
    name: '偏度因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'SKEW = skewness(daily_returns) over past 20 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: WorldQuant Alpha#39; Harvey & Siddique (2000); A-share validation: 华泰金工 2023《高阶矩 · 方向: lower',
    performance: 'IC≈-0.028, IR≈-0.15',
  },
  {
    id: 'f004',
    name: '最大日收益率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '情绪',
    definition: 'MAX = max(daily_return) over past 20 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: Bali, Cakici & Whitelaw (2011); A-shape validation: 中金公司 2023《极端收益率与A股横截面收益》, Bi · 方向: lower',
    performance: 'IC≈-0.052, IR≈-0.3',
  },
  {
    id: 'f005',
    name: '换手率波动因子',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'std(turnover_rate) over past 20 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: 国泰君安 2024《成交额与换手率因子体系》, 中信建投 2023《交易行为因子研究》 · 方向: lower',
    performance: 'IC≈-0.038, IR≈-0.22',
  },
  {
    id: 'f006',
    name: '异常换手率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'ABT = turnover_t / mean(turnover_{t-20:t-1}) - 1',
    applicable: '全市场 · lower为优',
    notes: '来源: Gargano & Rossi (2018); A-share: 华泰证券 2023《异常换手率与股票收益》, 聚宽社区 top-5因子 · 方向: lower',
    performance: 'IC≈-0.041, IR≈-0.24',
  },
  {
    id: 'f007',
    name: '52周高点距离',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: 'Close / max(Close over past 250 trading days) - 1',
    applicable: '全市场 · higher为优',
    notes: '来源: George & Hwang (2004); A-share validation: 中金公司 2023 《参考点效应与A股收益》, 天风证券 2024 · 方向: higher',
    performance: 'IC≈+0.035, IR≈0.2',
  },
  {
    id: 'f008',
    name: '历史最高价距离',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: 'Close / max(Close since listing) - 1',
    applicable: '全市场 · higher为优',
    notes: '来源: Li & Yu (2012); A-share validation: 华泰金工 2024《历史新高效应分析》, 聚宽社区 · 方向: higher',
    performance: 'IC≈+0.030, IR≈0.17',
  },
  {
    id: 'f009',
    name: 'WorldQuant Alpha#2',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: '(-1 × corr(rank(delta(log(volume), 2)), rank((close - open)/open), 6))',
    applicable: '全市场 · higher为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-share adaptation: 米筐社区2023 top-8, 聚宽社区 top-10 · 方向: higher',
    performance: 'IC≈+0.031, IR≈0.17',
  },
  {
    id: 'f010',
    name: 'WorldQuant Alpha#17',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'Rank of count of consecutive days where close > close_prev, over past 20 days',
    applicable: '全市场 · lower为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-share: 聚宽社区 top-20, BigQuant 2024多因子系列 · 方向: lower',
    performance: 'IC≈-0.025, IR≈-0.14',
  },
  {
    id: 'f011',
    name: 'WorldQuant Alpha#32',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'Correlation(close, market_cap, 20) weighted by volume, then add rank of turnover rate weighted by market cap',
    applicable: '全市场 · lower为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-shape adaptation: 米筐社区, BigQuant 2023 · 方向: lower',
    performance: 'IC≈-0.022, IR≈-0.12',
  },
  {
    id: 'f012',
    name: 'WorldQuant Alpha#53',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'rank((high - low) / close) over 20 days minus rank(((high - low) / close).shift(20) over 20 days)',
    applicable: '全市场 · higher为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-share: 米筐社区 top-15, 聚宽社区 · 方向: higher',
    performance: 'IC≈+0.024, IR≈0.13',
  },
  {
    id: 'f013',
    name: 'WorldQuant Alpha#57',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'Rank of (close - low) / (high - low) over 20 days, where close position in its range',
    applicable: '全市场 · higher为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-share: 聚宽社区 top-25 · 方向: higher',
    performance: 'IC≈+0.026, IR≈0.14',
  },
  {
    id: 'f014',
    name: 'WorldQuant Alpha#83',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'power(sign((vwap - close_prev) / close_prev), 2) × rank of volume change × sign of return',
    applicable: '全市场 · higher为优',
    notes: '来源: WorldQuant Alpha101 (2015); A-share: BigQuant 2024多因子研究 · 方向: higher',
    performance: 'IC≈+0.029, IR≈0.16',
  },
  {
    id: 'f015',
    name: '应计利润异象因子',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: 'Using ROE decomposition proxy: (Δcurrent_assets - Δcash - Δcurrent_liabilities + Δshort_debt - depreciation) / total_ass',
    applicable: '全市场 · lower为优',
    notes: '来源: Sloan (1996); A-share validation: 姜国华等 (2006), 华泰金工 2023《应计利润异象在A股的表现》, 中国社会科学院 · 方向: lower',
    performance: 'IC≈-0.033, IR≈-0.19',
  },
  {
    id: 'f016',
    name: 'EP因子（盈利收益率）',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: '1/PE_ttm, i.e., trailing 12-month earnings / market capitalization',
    applicable: '全市场 · higher为优',
    notes: '来源: Basu (1977); A-share validation: 中金公司 2023《价值因子体系重构》, 中信建投 2024《EP因子深度分析》 · 方向: higher',
    performance: 'IC≈+0.038, IR≈0.2',
  },
  {
    id: 'f017',
    name: 'PB×ROE复合因子',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: 'ROE / PB (simplified), i.e., profitability adjusted for valuation',
    applicable: '全市场 · higher为优',
    notes: '来源: 国泰君安 2024《PB-ROE框架下的选股因子》, 中金公司 2023《价值与质量的统一框架》 · 方向: higher',
    performance: 'IC≈+0.042, IR≈0.24',
  },
  {
    id: 'f018',
    name: 'EP分位数因子（行业中性化）',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: 'Cross-sectional percentile rank of E/P within each industry group',
    applicable: '全市场 · higher为优',
    notes: '来源: 中信建投 2023《行业中性化因子研究》, 天风证券 2024《改进的价值因子》 · 方向: higher',
    performance: 'IC≈+0.044, IR≈0.26',
  },
  {
    id: 'f019',
    name: '盈利稳定性因子',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: '1 / std(ROE over past 8 quarters), or simplified: 1 / std(PE_change over 20 periods)',
    applicable: '全市场 · higher为优',
    notes: '来源: 华泰证券 2024《盈利质量因子体系》, 国泰君安 2023《基本面动量因子》 · 方向: higher',
    performance: 'IC≈+0.035, IR≈0.19',
  },
  {
    id: 'f020',
    name: '市场Beta因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'Covariance(daily_returns, market_returns) / Variance(market_returns) over 60 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: CAPM (Sharpe 1964); A-shape: 中金公司 2023《低Beta异象在A股的持续性与反转》 · 方向: lower',
    performance: 'IC≈-0.030, IR≈-0.17',
  },
  {
    id: 'f021',
    name: '下行Beta因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'Covariance(daily_returns, market_returns) / Variance(market_returns) computed only on days when market return < 0, over ',
    applicable: '全市场 · lower为优',
    notes: '来源: Ang, Chen & Xing (2006); A-share: 国泰君安 2024《非对称风险因子研究》 · 方向: lower',
    performance: 'IC≈-0.036, IR≈-0.21',
  },
  {
    id: 'f022',
    name: '涨跌幅偏度因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'log(std(up_day_returns) / std(down_day_returns)) over 60 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: Chen, Hong & Stein (2001); A-share: 华泰金工 2023《涨跌不对称与A股预期收益》, 天风证券 2024 · 方向: lower',
    performance: 'IC≈-0.031, IR≈-0.17',
  },
  {
    id: 'f023',
    name: '价格延迟因子',
    source: 'public',
    origin: '联网挖掘',
    category: '微观结构',
    definition: 'Delay = 1 - (R-squared from regression of weekly returns on contemporaneous market return) / (R-squared from regression ',
    applicable: '全市场 · higher为优',
    notes: '来源: Hou & Moskowitz (2005); A-share: 华泰金工 2024《信息反应速度因子》, 中金公司 2023《A股价格延迟效应》 · 方向: higher',
    performance: 'IC≈+0.027, IR≈0.15',
  },
  {
    id: 'f024',
    name: 'Corwin-Schultz买卖价差估计',
    source: 'public',
    origin: '联网挖掘',
    category: '微观结构',
    definition: 'Based on daily high-low patterns. Sum over 2 consecutive days of [2(e^α - 1) / (1 + e^α)] where α depends on high-low ra',
    applicable: '全市场 · higher为优',
    notes: '来源: Corwin & Schultz (2012); A-share: 天风证券 2024《A股市场微观结构因子》, 华泰金工 2023 · 方向: higher',
    performance: 'IC≈+0.026, IR≈0.14',
  },
  {
    id: 'f025',
    name: 'R²因子（股价同步性）',
    source: 'public',
    origin: '联网挖掘',
    category: '微观结构',
    definition: 'R² from regression of daily returns on market returns over past 60 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: Morck, Yeung & Yu (2000); A-share: 中金公司 2023《股价同步性与A股横截面收益》, 华泰证券 2024 · 方向: lower',
    performance: 'IC≈-0.024, IR≈-0.13',
  },
  {
    id: 'f026',
    name: '零交易天数占比',
    source: 'public',
    origin: '联网挖掘',
    category: '微观结构',
    definition: 'count(volume = 0 or turnover_rate < threshold) / 20 trading days; use turnover_rate < 0.01% as proxy',
    applicable: '全市场 · higher为优',
    notes: '来源: Liu (2006); A-share: 中信建投 2023《A股停牌与零交易效应》, 华泰金工 2024 · 方向: higher',
    performance: 'IC≈+0.029, IR≈0.16',
  },
  {
    id: 'f027',
    name: '日内波动率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: '(high - low) / close averaged over 20 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: Parkinson (1980); A-share: 华泰金工 2023《波动率异象再审视》, 国泰君安 2024 · 方向: lower',
    performance: 'IC≈-0.027, IR≈-0.15',
  },
  {
    id: 'f028',
    name: '隔夜收益率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: 'Sum of (open_t / close_{t-1} - 1) over past 20 trading days',
    applicable: '全市场 · lower为优',
    notes: '来源: Berkman et al. (2012); A-share: 中金公司 2024《隔夜与日内收益分解》, 国泰君安 2023 · 方向: lower',
    performance: 'IC≈-0.040, IR≈-0.23',
  },
  {
    id: 'f029',
    name: '日内收益率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: 'Sum of (close_t / open_t - 1) over past 20 trading days',
    applicable: '全市场 · higher为优',
    notes: '来源: Lou, Polk, & Skouras (2019); A-share: 中金公司 2024《隔夜与日内收益分解》, 聚宽社区 · 方向: higher',
    performance: 'IC≈+0.033, IR≈0.18',
  },
  {
    id: 'f030',
    name: '成交量加权平均价偏离',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: '(close - VWAP_20d) / VWAP_20d, where VWAP = sum(close × volume) / sum(volume)',
    applicable: '全市场 · lower为优',
    notes: '来源: 国泰君安 2024《交易成本与VWAP因子》, 华泰证券 2023《交易行为因子》 · 方向: lower',
    performance: 'IC≈-0.025, IR≈-0.14',
  },
  {
    id: 'f031',
    name: '收益率峰度因子',
    source: 'public',
    origin: '联网挖掘',
    category: '波动',
    definition: 'Excess kurtosis of daily returns over past 60 trading days',
    applicable: '全市场 · higher为优',
    notes: '来源: Bollerslev et al. (2020); A-share: 华泰金工 2023《高阶矩因子研究》, 天风证券 2024 · 方向: higher',
    performance: 'IC≈+0.022, IR≈0.12',
  },
  {
    id: 'f032',
    name: '涨跌停触碰因子',
    source: 'public',
    origin: '联网挖掘',
    category: '情绪',
    definition: 'Count of days where (high-low)/close exceeds 0.095 (near limit-up/down) over 60 days, signed by return direction',
    applicable: '全市场 · lower为优',
    notes: '来源: 华泰证券 2024《涨跌停制度与A股因子》, 中信建投 2023《A股特有制度套利因子》 · 方向: lower',
    performance: 'IC≈-0.048, IR≈-0.28',
  },
  {
    id: 'f033',
    name: '流通市值换手率因子',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: 'market_cap × turnover_rate, i.e., dollar trading volume proxy',
    applicable: '全市场 · lower为优',
    notes: '来源: 中信建投 2023《流动性因子体系》, 国泰君安 2024《成交额因子研究》 · 方向: lower',
    performance: 'IC≈-0.034, IR≈-0.19',
  },
  {
    id: 'f034',
    name: '反转成交量确认因子',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: '5-day return × (-1) × (1 + sign of excess volume), where excess_volume = volume / mean(volume_{t-10:t-1}) - 1',
    applicable: '全市场 · higher为优',
    notes: '来源: 聚宽社区 2023 top-3因子; 华泰证券 2024《成交量增强的动量反转因子》 · 方向: higher',
    performance: 'IC≈+0.046, IR≈0.27',
  },
  {
    id: 'f035',
    name: '小市值波动因子',
    source: 'public',
    origin: '联网挖掘',
    category: '规模',
    definition: 'rank(std_daily_returns_20d) × rank(-market_cap), i.e., interaction of volatility and size',
    applicable: '全市场 · lower为优',
    notes: '来源: 华泰证券 2024《市值与波动率的交互效应》, 中金公司 2023《A股小市值效应再验证》 · 方向: lower',
    performance: 'IC≈-0.055, IR≈-0.32',
  },
  {
    id: 'f036',
    name: '格雷厄姆内在价值偏离',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: '(Close/Book_Value - sqrt(22.5 × EPS × BVPS) / BVPS), simplified: (PB - sqrt(22.5 × ROE)) / PB',
    applicable: '全市场 · lower为优',
    notes: '来源: Graham & Dodd; A-share adaptation: 聚宽社区 top-12, BigQuant 2023《价值投资因子新编》 · 方向: lower',
    performance: 'IC≈-0.029, IR≈-0.16',
  },
  {
    id: 'f037',
    name: '融资融券余额变化率',
    source: 'public',
    origin: '联网挖掘',
    category: '资金流',
    definition: 'Proxy: abnormal turnover rate change as a signal of leveraged positioning. (turnover_20d - turnover_60d) / turnover_60d',
    applicable: '全市场 · lower为优',
    notes: '来源: 中金公司 2024《融资融券与A股因子》, 华泰证券 2023《杠杆资金行为因子》 · 方向: lower',
    performance: 'IC≈-0.036, IR≈-0.21',
  },
  {
    id: 'f038',
    name: '大宗交易折溢价因子',
    source: 'public',
    origin: '联网挖掘',
    category: '资金流',
    definition: 'Proxy: volume_spike / typical_volume. Volume spikes relative to average may signal block trades. (max_volume_5d / mean_v',
    applicable: '全市场 · lower为优',
    notes: '来源: 华泰证券 2024《大宗交易的信息含量》, 国泰君安 2023《事件驱动因子研究》 · 方向: lower',
    performance: 'IC≈-0.024, IR≈-0.13',
  },
  {
    id: 'f039',
    name: '分析师预期分散度因子',
    source: 'public',
    origin: '联网挖掘',
    category: '情绪',
    definition: 'Proxy: PE_range / PE_median over past observations. std(PE_change_20d) / abs(PE) normalized',
    applicable: '全市场 · lower为优',
    notes: '来源: Diether, Malloy & Scherbina (2002); A-share: 中金公司 2023《分析师预期与A股收益》, 天风证券 2024 · 方向: lower',
    performance: 'IC≈-0.031, IR≈-0.17',
  },
  {
    id: 'f040',
    name: 'PE变化趋势因子',
    source: 'public',
    origin: '联网挖掘',
    category: '价值',
    definition: '(PE_current - PE_60d_ago) / PE_60d_ago, i.e., 3-month change in PE ratio',
    applicable: '全市场 · higher为优',
    notes: '来源: 天风证券 2024《估值变化与A股截面收益》, 国泰君安 2023《基本面动量因子2.0》 · 方向: higher',
    performance: 'IC≈+0.034, IR≈0.19',
  },
  {
    id: 'f041',
    name: '成交量冲击因子',
    source: 'public',
    origin: '联网挖掘',
    category: '量价',
    definition: '(volume_current - mean_volume_20d) / std(volume_20d), cross-sectional z-score of abnormal volume',
    applicable: '全市场 · lower为优',
    notes: '来源: 聚宽社区 2024 top-8; 华泰证券 2023《量价因子新范式》 · 方向: lower',
    performance: 'IC≈-0.037, IR≈-0.21',
  },
  {
    id: 'f042',
    name: '行业动量因子',
    source: 'public',
    origin: '联网挖掘',
    category: '动量',
    definition: 'Average return of all stocks in the same industry over past 20 trading days (leave-one-out)',
    applicable: '全市场 · higher为优',
    notes: '来源: Moskowitz & Grinblatt (1999); A-share: 中金公司 2023《行业动量与A股选股》, 中信建投 2024 · 方向: higher',
    performance: 'IC≈+0.040, IR≈0.23',
  },